-- MySQL Script generated by MySQL Workbench
-- Tue Jul 16 03:53:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS PersonalFinanceTrackerDB;
CREATE DATABASE PersonalFinanceTrackerDB;
USE PersonalFinanceTrackerDB;
-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `FullName` VARCHAR(100) GENERATED ALWAYS AS (CONCAT(FirstName, ' ', LastName)) VIRTUAL,
  `Password` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `DateOfBirth` DATE NULL,
  `SSN` VARCHAR(11) NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `ssn_UNIQUE` (`SSN` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Goal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Goal` ;

CREATE TABLE IF NOT EXISTS `Goal` (
  `GoalId` INT NOT NULL AUTO_INCREMENT,
  `CurrentAmount` DECIMAL(10,2) NOT NULL,
  `TargetAmount` DECIMAL(10,2) NOT NULL,
  `DateCreated` DATETIME NOT NULL DEFAULT Current_Timestamp,
  `Status` TINYINT NOT NULL,
  `Type` ENUM('Long', 'Short') NOT NULL,
  PRIMARY KEY (`GoalId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BudgetPlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BudgetPlan` ;

CREATE TABLE IF NOT EXISTS `BudgetPlan` (
  `BudgetPlanId` INT NOT NULL AUTO_INCREMENT,
  `TotalBudget` DECIMAL(10,2) NOT NULL,
  `SetForDays` INT NOT NULL,
  PRIMARY KEY (`BudgetPlanId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `AccountId` INT NOT NULL AUTO_INCREMENT,
  `UserId` INT NULL,
  `CreatedDate` TIMESTAMP NOT NULL DEFAULT Current_Timestamp,
  `Status` VARCHAR(20) NOT NULL,
  `GoalId` INT NULL,
  `BudgetPlanId` INT NULL,
  PRIMARY KEY (`AccountId`),
  INDEX `fk_account_user_id_idx` (`UserId` ASC) INVISIBLE,
  UNIQUE INDEX `GoalId_UNIQUE` (`GoalId` ASC) VISIBLE,
  UNIQUE INDEX `BudgetPlanId_UNIQUE` (`BudgetPlanId` ASC) VISIBLE,
  CONSTRAINT `fk_account_user_id`
    FOREIGN KEY (`UserId`)
    REFERENCES `User` (`UserId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_account_goalid`
    FOREIGN KEY (`GoalId`)
    REFERENCES `Goal` (`GoalId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_budgetplanid`
    FOREIGN KEY (`BudgetPlanId`)
    REFERENCES `BudgetPlan` (`BudgetPlanId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Category` ;

CREATE TABLE IF NOT EXISTS `Category` (
  `CategoryId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`CategoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction` ;

CREATE TABLE IF NOT EXISTS `Transaction` (
  `TransactionId` INT NOT NULL AUTO_INCREMENT,
  `Amount` INT NOT NULL,
  `DateTime` DATETIME NOT NULL,
  `TransactionType` ENUM('Income', 'Expense') NOT NULL,
  `AccountId` INT NULL,
  `CategoryId` INT NULL,
  PRIMARY KEY (`TransactionId`),
  UNIQUE INDEX `AccountId_UNIQUE` (`AccountId` ASC) VISIBLE,
  INDEX `fk_transaction_categoryid_idx` (`CategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_accountid`
    FOREIGN KEY (`AccountId`)
    REFERENCES `Account` (`AccountId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaction_categoryid`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `Category` (`CategoryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BudgetAlert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BudgetAlert` ;

CREATE TABLE IF NOT EXISTS `BudgetAlert` (
  `AlertId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(20) NOT NULL,
  `Description` TEXT NULL,
  `Threshold` SMALLINT(25) NULL,
  `BudgetPlanId` INT NOT NULL,
  PRIMARY KEY (`AlertId`),
  UNIQUE INDEX `BudgetPlanId_UNIQUE` (`BudgetPlanId` ASC) VISIBLE,
  CONSTRAINT `fk_budgetalert_budgetplanid`
    FOREIGN KEY (`BudgetPlanId`)
    REFERENCES `BudgetPlan` (`BudgetPlanId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SharedSavingsGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SharedSavingsGroup` ;

CREATE TABLE IF NOT EXISTS `SharedSavingsGroup` (
  `GroupID` INT NOT NULL AUTO_INCREMENT,
  `GroupName` VARCHAR(15) NOT NULL,
  `Description` TEXT NULL,
  PRIMARY KEY (`GroupID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserSharedSavingsGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserSharedSavingsGroup` ;

CREATE TABLE IF NOT EXISTS `UserSharedSavingsGroup` (
  `UserId` INT NOT NULL,
  `GroupId` INT NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `DateJoined` DATETIME NOT NULL,
  PRIMARY KEY (`GroupId`, `UserId`),
  INDEX `fk_sharedsavingsgroup_groupid_idx` (`GroupId` ASC) VISIBLE,
  CONSTRAINT `fk_sharedsavingsgroup_userid`
    FOREIGN KEY (`UserId`)
    REFERENCES `User` (`UserId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sharedsavingsgroup_groupid`
    FOREIGN KEY (`GroupId`)
    REFERENCES `SharedSavingsGroup` (`GroupID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CreditScoreInsights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CreditScoreInsights` ;

CREATE TABLE IF NOT EXISTS `CreditScoreInsights` (
  `InsightId` INT NOT NULL AUTO_INCREMENT,
  `DateCreated` DATETIME NOT NULL DEFAULT Current_TimeStamp,
  `FinancialBehaviorAnalysis` VARCHAR(250) NOT NULL,
  `SSN` VARCHAR(11) NULL,
  PRIMARY KEY (`InsightId`),
  UNIQUE INDEX `UserId_UNIQUE` (`SSN` ASC) VISIBLE,
  CONSTRAINT `fk_creditscoreinsights_ssn`
    FOREIGN KEY (`SSN`)
    REFERENCES `User` (`SSN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Notification` ;

CREATE TABLE IF NOT EXISTS `Notification` (
  `NotificationId` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL DEFAULT Current_Timestamp,
  `Message` MEDIUMTEXT NOT NULL,
  `BudgetAlertId` INT NOT NULL,
  PRIMARY KEY (`NotificationId`),
  UNIQUE INDEX `BudgetAlertId_UNIQUE` (`BudgetAlertId` ASC) VISIBLE,
  CONSTRAINT `fk_notification_budgetalertid`
    FOREIGN KEY (`BudgetAlertId`)
    REFERENCES `BudgetAlert` (`AlertId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserNotifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserNotifications` ;

CREATE TABLE IF NOT EXISTS `UserNotifications` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `NotificationId` INT NOT NULL,
  `Status` TINYINT(5) NOT NULL,
  INDEX `fk_usernotification_userid_idx` (`UserId` ASC) VISIBLE,
  PRIMARY KEY (`UserId`, `NotificationId`),
  CONSTRAINT `fk_usernotification_userid`
    FOREIGN KEY (`UserId`)
    REFERENCES `User` (`UserId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usernotification_notificationid`
    FOREIGN KEY (`NotificationId`)
    REFERENCES `Notification` (`NotificationId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinancialNewsFeed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinancialNewsFeed` ;

CREATE TABLE IF NOT EXISTS `FinancialNewsFeed` (
  `NewsId` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(20) NOT NULL,
  `Content` LONGTEXT NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`NewsId`),
  UNIQUE INDEX `UserId_UNIQUE` (`UserId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserFinancialNewsFeed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UserFinancialNewsFeed` ;

CREATE TABLE IF NOT EXISTS `UserFinancialNewsFeed` (
  `UserId` INT NOT NULL,
  `NewsId` INT NOT NULL,
  `ViewedDate` DATETIME NOT NULL,
  `GeneratedDate` DATETIME NOT NULL,
  PRIMARY KEY (`UserId`, `NewsId`),
  INDEX `fk_userfinancialnewsfeed_newsid_idx` (`NewsId` ASC) VISIBLE,
  CONSTRAINT `fk_userfinancialnewsfeed_userid`
    FOREIGN KEY (`UserId`)
    REFERENCES `User` (`UserId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_userfinancialnewsfeed_newsid`
    FOREIGN KEY (`NewsId`)
    REFERENCES `FinancialNewsFeed` (`NewsId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CreditScoreGoals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CreditScoreGoals` ;

CREATE TABLE IF NOT EXISTS `CreditScoreGoals` (
  `ScoreGoalId` INT NOT NULL AUTO_INCREMENT,
  `Timeframe` VARCHAR(45) NOT NULL,
  `TargetScore` SMALLINT NOT NULL,
  `CurrentScore` SMALLINT NOT NULL,
  `DateSet` DATETIME NOT NULL DEFAULT Current_Timestamp,
  `SSN` VARCHAR(11) NULL,
  PRIMARY KEY (`ScoreGoalId`),
  UNIQUE INDEX `SSN_UNIQUE` (`SSN` ASC) VISIBLE,
  CONSTRAINT `fk_creditscoregoals_ssn`
    FOREIGN KEY (`SSN`)
    REFERENCES `User` (`SSN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FinancialInstitution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FinancialInstitution` ;

CREATE TABLE IF NOT EXISTS `FinancialInstitution` (
  `InstitutionId` INT NOT NULL AUTO_INCREMENT,
  `ContactInfo` VARCHAR(45) NULL,
  `Name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`InstitutionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountFinancialInstitution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountFinancialInstitution` ;

CREATE TABLE IF NOT EXISTS `AccountFinancialInstitution` (
  `AccountId` INT NOT NULL,
  `InstitutionId` INT NOT NULL,
  `AccountType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AccountId`, `InstitutionId`),
  INDEX `fk_accountfinancialinstitution_instituionid_idx` (`InstitutionId` ASC) VISIBLE,
  CONSTRAINT `fk_accountfinancialinstitution_accountid`
    FOREIGN KEY (`AccountId`)
    REFERENCES `Account` (`AccountId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_accountfinancialinstitution_institutionid`
    FOREIGN KEY (`InstitutionId`)
    REFERENCES `FinancialInstitution` (`InstitutionId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InvestmentPortfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InvestmentPortfolio` ;

CREATE TABLE IF NOT EXISTS `InvestmentPortfolio` (
  `PortfolioId` INT NOT NULL AUTO_INCREMENT,
  `AssetType` VARCHAR(15) NULL,
  `AssetValue` VARCHAR(45) NULL,
  `AccountId` INT NULL,
  PRIMARY KEY (`PortfolioId`),
  INDEX `fk_investmentportfolio_accountid_idx` (`AccountId` ASC) VISIBLE,
  CONSTRAINT `fk_investmentportfolio_accountid`
    FOREIGN KEY (`AccountId`)
    REFERENCES `Account` (`AccountId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GroupGoal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GroupGoal` ;

CREATE TABLE IF NOT EXISTS `GroupGoal` (
  `GoalId` INT NOT NULL,
  `GroupId` INT NOT NULL,
  `ContributionAmount` DECIMAL(10,2) NOT NULL,
  `Comment` TEXT NULL,
  PRIMARY KEY (`GoalId`, `GroupId`),
  INDEX `fk_groupgoal_groupid_idx` (`GroupId` ASC) VISIBLE,
  CONSTRAINT `fk_groupgoal_groupid`
    FOREIGN KEY (`GroupId`)
    REFERENCES `SharedSavingsGroup` (`GroupID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_groupgoal_goalid`
    FOREIGN KEY (`GoalId`)
    REFERENCES `Goal` (`GoalId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DigitalReceiptsOrganizer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DigitalReceiptsOrganizer` ;

CREATE TABLE IF NOT EXISTS `DigitalReceiptsOrganizer` (
  `ReceiptId` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `OCRData` VARCHAR(455) NULL,
  `AccountId` INT NOT NULL,
  `TransactionId` INT NULL,
  PRIMARY KEY (`ReceiptId`, `AccountId`),
  UNIQUE INDEX `AccountId_UNIQUE` (`AccountId` ASC) VISIBLE,
  INDEX `fk_digitalreceiptsorganizer_transactionid_idx` (`TransactionId` ASC) VISIBLE,
  CONSTRAINT `fk_digitalreceiptsorganizer_accountid`
    FOREIGN KEY (`AccountId`)
    REFERENCES `Account` (`AccountId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_digitalreceiptsorganizer_transactionid`
    FOREIGN KEY (`TransactionId`)
    REFERENCES `Transaction` (`TransactionId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DebtManagement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DebtManagement` ;

CREATE TABLE IF NOT EXISTS `DebtManagement` (
  `ManagementId` INT NOT NULL AUTO_INCREMENT,
  `DebtType` VARCHAR(45) NOT NULL,
  `AmountOwed` DECIMAL(10,2) NOT NULL,
  `AccountId` INT NULL,
  PRIMARY KEY (`ManagementId`),
  INDEX `fk_debtmanagement_accountid_idx` (`AccountId` ASC) VISIBLE,
  CONSTRAINT `fk_debtmanagement_accountid`
    FOREIGN KEY (`AccountId`)
    REFERENCES `Account` (`AccountId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ScheduledPayment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ScheduledPayment` ;

CREATE TABLE IF NOT EXISTS `ScheduledPayment` (
  `PaymentId` INT NOT NULL AUTO_INCREMENT,
  `PaymentDate` DATETIME NOT NULL,
  `Amount` DECIMAL(10,2) NOT NULL,
  `Frequency` VARCHAR(15) NULL,
  `AccountId` INT NOT NULL,
  PRIMARY KEY (`PaymentId`),
  UNIQUE INDEX `AccountId_UNIQUE` (`AccountId` ASC) VISIBLE,
  CONSTRAINT `fk_scheduledpayment_accountid`
    FOREIGN KEY (`AccountId`)
    REFERENCES `Account` (`AccountId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Report` ;

CREATE TABLE IF NOT EXISTS `Report` (
  `ReportId` INT NOT NULL AUTO_INCREMENT,
  `AccountId` INT NOT NULL,
  `GeneratedDate` DATETIME NOT NULL DEFAULT Current_Timestamp,
  `Description` LONGTEXT NOT NULL,
  PRIMARY KEY (`ReportId`),
  INDEX `fk_report_accountid_idx` (`AccountId` ASC) VISIBLE,
  CONSTRAINT `fk_report_accountid`
    FOREIGN KEY (`AccountId`)
    REFERENCES `Account` (`AccountId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SubscriptionManagement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SubscriptionManagement` ;

CREATE TABLE IF NOT EXISTS `SubscriptionManagement` (
  `SubscriptionId` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  `ServiceName` VARCHAR(45) NOT NULL,
  `ScheduledPaymentId` INT NOT NULL,
  PRIMARY KEY (`SubscriptionId`),
  UNIQUE INDEX `AccountId_UNIQUE` (`ScheduledPaymentId` ASC) VISIBLE,
  CONSTRAINT `fk_subscriptionmanagement_scheduledpaymentid`
    FOREIGN KEY (`ScheduledPaymentId`)
    REFERENCES `ScheduledPayment` (`PaymentId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Currency` ;

CREATE TABLE IF NOT EXISTS `Currency` (
  `CurrencyId` INT NOT NULL AUTO_INCREMENT,
  `CurrencyCode` VARCHAR(3) NOT NULL,
  `CurrencyName` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`CurrencyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ExchangeRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ExchangeRate` ;

CREATE TABLE IF NOT EXISTS `ExchangeRate` (
  `ExchangeRateId` INT NOT NULL AUTO_INCREMENT,
  `FromCurrencyId` INT NOT NULL,
  `ToCurrencyId` INT NOT NULL,
  `Rate` DECIMAL(10,6) NOT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`ExchangeRateId`),
  CONSTRAINT `fk_exchangerate_fromcurrency`
    FOREIGN KEY (`FromCurrencyId`)
    REFERENCES `Currency` (`CurrencyId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_exchangerate_tocurrency`
    FOREIGN KEY (`ToCurrencyId`)
    REFERENCES `Currency` (`CurrencyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CurrencyConvertor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CurrencyConvertor` ;

CREATE TABLE IF NOT EXISTS `CurrencyConvertor` (
  `ConvertorId` INT NOT NULL AUTO_INCREMENT,
  `OriginalAmount` DECIMAL(10,2) NOT NULL,
  `ConvertedAmount` DECIMAL(10,2) NOT NULL,
  `ExchangeRateId` INT NOT NULL,
  PRIMARY KEY (`ConvertorId`),
  INDEX `fk_currencyconvertor_exchangerateid_idx` (`ExchangeRateId` ASC) VISIBLE,
  CONSTRAINT `fk_currencyconvertor_exchangerateid`
    FOREIGN KEY (`ExchangeRateId`)
    REFERENCES `ExchangeRate` (`ExchangeRateId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TransactionCurrencyConvertor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransactionCurrencyConvertor` ;

CREATE TABLE IF NOT EXISTS `TransactionCurrencyConvertor` (
  `ConversionId` INT NOT NULL AUTO_INCREMENT,
  `TransactionId` INT NOT NULL,
  `ConversionTimestamp` DATETIME NOT NULL,
  `ConversionFee` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`TransactionId`),
  INDEX `fk_transactioncurrencyconvertor_transactionid_idx` (`TransactionId` ASC) VISIBLE,
  CONSTRAINT `fk_transactioncurrencyconvertor_transactionid`
    FOREIGN KEY (`TransactionId`)
    REFERENCES `Transaction` (`TransactionId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transactioncurrencyconvertor_convertorid`
    FOREIGN KEY (`ConversionId`)
    REFERENCES `CurrencyConvertor` (`ConvertorId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CategoryReport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CategoryReport` ;

CREATE TABLE IF NOT EXISTS `CategoryReport` (
  `ReportId` INT NOT NULL,
  `CategoryId` INT NOT NULL,
  `TotalSpent` DECIMAL(10,2) NOT NULL,
  `Description` TEXT NULL,
  PRIMARY KEY (`ReportId`, `CategoryId`),
  INDEX `fk_categoryreport_catergoryid_idx` (`CategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_categoryreport_reportid`
    FOREIGN KEY (`ReportId`)
    REFERENCES `Report` (`ReportId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_categoryreport_catergoryid`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `Category` (`CategoryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BudgetPlanCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BudgetPlanCategory` ;

CREATE TABLE IF NOT EXISTS `BudgetPlanCategory` (
  `CategoryId` INT NOT NULL,
  `PlanId` INT NOT NULL,
  `AllocatedAmount` DECIMAL(10,2) NOT NULL,
  `Notes` VARCHAR(255) NULL,
  PRIMARY KEY (`CategoryId`, `PlanId`),
  INDEX `fk_budgetplancategory_planid_idx` (`PlanId` ASC) VISIBLE,
  CONSTRAINT `fk_budgetplancategory_categoryid`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `Category` (`CategoryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_budgetplancategory_planid`
    FOREIGN KEY (`PlanId`)
    REFERENCES `BudgetPlan` (`BudgetPlanId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
